# Run

name: Manual

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get python's version
        run: python3 --version
        
      #- name: View environment
      #  run: echo "${{toJson(github)}}"
        
      - name: Run
        run: cd $HOME/work/telegram/TrafficBot/ && python3 bot.py
